development:
  adapter: postgresql
  encoding: unicode
  database: tournament_tool_development
  pool: 5
  username: postgres
  password: postgres

test: &test
  adapter: postgresql
  encoding: unicode
  database: tournament_tool_test
  pool: 5
  username: postgres
  password: postgres

cucumber:
  <<: *test
