development:
  adapter: postgresql
  encoding: unicode
  database: anr_tournaments_development
  pool: 5
  username: postgres
  password: postgres

test: &test
  adapter: postgresql
  encoding: unicode
  database: anr_tournaments_test
  pool: 5
  username: postgres
  password: postgres

cucumber:
  <<: *test
